AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Pizza Product Service
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    OpenApiVersion: "3.0"
    CacheClusterEnabled: !If [EnableCache, true, false]
    CacheClusterSize: "0.5"

Parameters:
  Environment:
    Description: The environment
    Type: String

Conditions:
  EnableCache: !Equals [ !Ref Environment, prod]

Mappings:
  EnvironmentMap:
    dev:
      DomainName: "api.dev.serverlesspizza.com"
    prod:
      DomainName: "api.serverlesspizza.com"

Resources:
  ProductTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: productId
          AttributeType: S
      TableName: !Join
        - '-'
        - - !Ref Environment
          - 'products'
      KeySchema:
        - AttributeName: productId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Join
        - '-'
        - - 'serverlesspizza'
          - !Ref Environment
          - 'products-api'
      StageName: !Ref Environment
      EndpointConfiguration: REGIONAL
      MethodSettings:
        - HttpMethod: '*'
          ResourcePath: '/*'
          CachingEnabled: !If [EnableCache, true, false]
          CacheTtlInSeconds: 3600 # 24 hours
          LoggingLevel: INFO
          DataTraceEnabled: true
          MetricsEnabled: true
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "product-service API"
        paths:
          /:
            options:
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProductServiceFunction.Arn}/invocations
                httpMethod: "POST"
                type: "aws_proxy"
            get:
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProductServiceFunction.Arn}/invocations
                httpMethod: "POST"
                type: "aws_proxy"
              security:
                - AWS_IAM: []
        openapi: "3.0"
        components:
          securitySchemes:
            AWS_IAM:
              x-amazon-apigateway-authtype: "awsSigv4"
              type: "apiKey"
              name: "Authorization"
              in: "header"

  ProductServiceFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessRestApi}/*/*/
      FunctionName: !Ref ProductServiceFunction

  ProductServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join
        - '-'
        - - 'serverlesspizza'
          - !Ref Environment
          - 'products'
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
      Handler: com.serverlesspizza.service.product.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/product-service-1.0-SNAPSHOT-lambda-package.zip
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaExecute
        - AmazonDynamoDBFullAccess

  ProductsApiBasePathMapping:
    DependsOn:
      - ServerlessRestApiStage
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: products
      DomainName: !FindInMap [EnvironmentMap, !Ref Environment, DomainName]
      RestApiId: !Ref ServerlessRestApi
      Stage: !Ref Environment
